---
- name: SSH Push
  hosts: all
  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"